export const ADD_AMT = "ADD_AMOUNT"
export const REMOVE_AMT = "REMOVE_AMOUNT"

export const REMOVE_LOCAL_STORAGE = "REMOVE_LOCAL_STORAGE"

export const CREDIT_MODALBOX = "CREDIT_MODALBOX"
export const DEBIT_MODALBOX = "DEBIT_MODALBOX"

export const DELETE_BY_ID = "DELETE_BY_ID"


export const GET_TOTAL_SUCCESS = "GET_TOTAL_SUCCESS"
export const GET_TOTAL_START = "GET_TOTAL_START"

export const GET_DATA_STARTED = "GET_DATA_STARTED"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"


export const GET_DATA_BYTYPE_STARTED = "GET_DATA_BYTYPE_STARTED"
export const GET_DATA_BYTYPE_SUCCESS = "GET_DATA_BYTYPE_SUCCESS"